ALTER TABLE meteo_data ADD COLUMN wind_gust_knots NUMERIC DEFAULT NULL
ALTER TABLE meteo_data ADD COLUMN dew_point_cels NUMERIC DEFAULT NULL
ALTER TABLE "meteo_data" ALTER COLUMN  "rain_today_mm" TYPE NUMERIC
UPDATE locations SET height_asl_m=330 WHERE id=12;
UPDATE locations SET height_asl_m=267 WHERE id=11;
SELECT * FROM locations;


ALTER TABLE ws_capabilities
RENAME COLUMN equilibrium_moisture_content TO rel_equilibrium_moisture_content;

-- GET LAST OBSERVATION'S TIMESTAMP FOR EACH STATION
SELECT DISTINCT ON (LOCATION_ID) LOCATION_ID, ID, TIMESTAMP_WS FROM METEO_DATA ORDER BY LOCATION_ID, TIMESTAMP_WS DESC;

-- GET TOTAL NUMBER OF OBSERVATIONS
SELECT COUNT(*) FROM METEO_DATA;

-- GET NUMBER OF OBSERVATIONS FOR EACH STATION
SELECT LOCATIONS.ID, LOCATIONS.NAME, LOCATIONS.TOWN, COUNT(*) FROM meteo_data, LOCATIONS WHERE METEO_DATA.LOCATION_ID=LOCATIONS.ID GROUP BY LOCATIONS.ID ORDER BY LOCATIONS.ID;

-- GET NUMBER OF OBSERVATIONS FOR EACH TOWN
SELECT LOCATIONS.TOWN, COUNT(*) FROM meteo_data, LOCATIONS WHERE METEO_DATA.LOCATION_ID=LOCATIONS.ID GROUP BY LOCATIONS.TOWN ORDER BY LOCATIONS.TOWN;

--- TODAY'S MIN MAX TEMPERATURES FOR EACH LOCATION
SELECT LOCATION_ID, DATE(timestamp_ws), MIN(TEMPERATURE_CELS), MAX(TEMPERATURE_CELS) FROM METEO_DATA WHERE DATE(timestamp_ws)=DATE(NOW()) GROUP BY LOCATION_ID, DATE(timestamp_ws);

--- WRONG wind_force_beaufort_desc COLUMN CONTENT DISCOVERY
SELECT wind_force_beaufort_desc, COUNT(*) FROM METEO_DATA WHERE wind_force_beaufort_desc IN ('N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'WNW', 'NW', 'NNW') GROUP BY wind_force_beaufort_desc;

SELECT id, location_id, timestamp_ws, wind_force_beaufort_desc FROM METEO_DATA WHERE wind_force_beaufort_desc='W' ORDER BY ID DESC;

SELECT * FROM METEO_DATA WHERE LOCATION_ID>=26 ORDER BY ID DESC;

SELECT id, location_id, timestamp_ws, wind_force_beaufort_desc from METEO_DATA WHERE LOCATION_ID>=26 ORDER BY ID DESC;
