ALTER TABLE meteo_data ADD COLUMN wind_gust_knots NUMERIC DEFAULT NULL
ALTER TABLE meteo_data ADD COLUMN dew_point_cels NUMERIC DEFAULT NULL
ALTER TABLE "meteo_data" ALTER COLUMN  "rain_today_mm" TYPE NUMERIC
UPDATE locations SET height_asl_m=330 WHERE id=12;
UPDATE locations SET height_asl_m=267 WHERE id=11;
SELECT * FROM locations;


ALTER TABLE ws_capabilities
RENAME COLUMN equilibrium_moisture_content TO rel_equilibrium_moisture_content;

-- GET LAST OBSERVATION'S TIMESTAMP FOR EACH STATION
SELECT DISTINCT ON (LOCATION_ID) LOCATION_ID, ID, TIMESTAMP_WS FROM METEO_DATA ORDER BY LOCATION_ID, TIMESTAMP_WS DESC;

-- GET TOTAL NUMBER OF OBSERVATIONS
SELECT COUNT(*) FROM METEO_DATA;

-- GET NUMBER OF OBSERVATIONS FOR EACH STATION
SELECT LOCATIONS.ID, LOCATIONS.NAME, LOCATIONS.TOWN, COUNT(*) FROM meteo_data, LOCATIONS WHERE METEO_DATA.LOCATION_ID=LOCATIONS.ID GROUP BY LOCATIONS.ID ORDER BY LOCATIONS.ID;

-- GET NUMBER OF OBSERVATIONS FOR EACH TOWN
SELECT LOCATIONS.TOWN, COUNT(*) FROM meteo_data, LOCATIONS WHERE METEO_DATA.LOCATION_ID=LOCATIONS.ID GROUP BY LOCATIONS.TOWN ORDER BY LOCATIONS.TOWN;